routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'CcpsCore\HomeController@index')->name('home');
Route::get('home', 'CcpsCore\HomeController@index');

Route::group(['prefix' => 'account'], function () {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::post('/settings', 'CcpsCore\AccountController@updateSettings')->name('account.settings.update');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', 'CcpsCore\AccountController@tokens')->name('index');
        Route::get('create', 'CcpsCore\AccountController@createToken')->name('create');
        Route::post('/', 'CcpsCore\AccountController@storeToken')->name('store');
        Route::get('{token}', 'CcpsCore\AccountController@editToken')->name('edit');
        Route::patch('{token}', 'CcpsCore\AccountController@updateToken')->name('update');
        Route::delete('{token}', 'CcpsCore\AccountController@revokeToken')->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', 'CcpsCore\AccountController@notifications')->name('account.notifications.index');
        Route::get('/channels/create', 'CcpsCore\AccountController@createChannel')->name('account.notifications.channels.create');
        Route::post('/channels/create', 'CcpsCore\AccountController@storeChannel')->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', 'CcpsCore\AccountController@destroyChannel')->name('account.notifications.channels.destroy');
        Route::get(
            '/channels/{channel}/resend-verification',
            'CcpsCore\ChannelVerificationController@resend'
        )->name('account.notifications.channels.resend-verification');
        Route::get(
            '/channels/{channel}/verify',
            'CcpsCore\ChannelVerificationController@verify'
        )->name('account.notifications.channels.verify');
        Route::get(
            '/channels/{channel}/test',
            'CcpsCore\ChannelVerificationController@test'
        )->name('account.notifications.channels.test');

        Route::get('/configure', 'CcpsCore\AccountController@configure')->name('account.notifications.configure');
        Route::post('/configure', 'CcpsCore\AccountController@configureSave')->name('account.notifications.configure.save');
    });
});

// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();
// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');


// Route::get('apistats', '\Uncgits\CcpsApiLog\Http\Controllers\StatisticsController@index');


// -----------------------
// Google Viewer app routes
// -----------------------

Route::group(['prefix' => 'google', 'middleware' => ['auth']], function () {
    Route::get('/', 'GoogleController@index')->name('google');
    Route::get('/info', 'GoogleController@info')->name('google.info');
    Route::group(['prefix' => 'activity'], function () {
        Route::get('/', 'GoogleController@getActivity')->name('google.activity.index');
        Route::post('/', 'GoogleController@getActivity')->name('google.activity.index');

        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
    });
    Route::group(['prefix' => 'users'], function () {
        Route::post('/suspend', 'GoogleController@suspendUser')->name('google.users.suspend');

        Route::get('/show/', 'GoogleController@showUser')->name('google.users.show');

        Route::get('bulk-rename', 'Google\BulkActionController@rename')->name('google.users.bulk-rename');
        Route::post('bulk-rename', 'Google\BulkActionController@confirmRename')->name('google.users.bulk-rename-confirm');
        Route::post('bulk-rename/confirm', 'Google\BulkActionController@performRename')->name('google.users.bulk-rename-perform');

        Route::get('bulk-delete', 'Google\BulkActionController@delete')->name('google.users.bulk-delete');
        Route::post('bulk-delete', 'Google\BulkActionController@confirmDelete')->name('google.users.bulk-delete-confirm');
        Route::post('bulk-delete/confirm', 'Google\BulkActionController@performDelete')->name('google.users.bulk-delete-perform');

        Route::get('/admins', 'GoogleController@getAdmins');
        Route::get('/{key}', 'GoogleController@showUser')->name('google.users.key');
        Route::get('/{key}/logins', 'GoogleController@showUserLogins')->name('google.users.logins');
        Route::get('/{key}/email/', 'Google\UserEmailController@showUserEmail')->name('google.users.email');
        Route::get('/{key}/groups/', 'Google\UserGroupsController@showUserGroups')->name('google.users.groups');

        Route::get('/', 'GoogleController@getUsers')->name('google.users.index');

        Route::post('/', 'GoogleController@getUsers')->name('google.users.index');


        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
    });
    Route::group(['prefix' => 'groups'], function () {
        Route::get('/', 'Google\GroupController@index')->name('google.groups.index');
        Route::get('create', 'Google\GroupController@create')->name('google.groups.create');
        Route::get('sync', 'Google\GroupController@sync')->name('google.groups.sync');
        Route::get('all', 'Google\GroupController@all')->name('google.groups.all');
        Route::post('store', 'Google\GroupController@store')->name('google.groups.store');
        Route::get('{group}/edit', 'Google\GroupController@edit')->name('google.groups.edit');
        Route::post('{group}/edit', 'Google\GroupController@update')->name('google.groups.update');

        Route::get('/queue', 'Google\GroupController@getQueue')->name('google.groups.queue');

        Route::get('{group}/members', 'Google\GroupController@editMembers')->name('google.groups.members.edit');
        Route::post('{group}/members', 'Google\GroupController@updateMembers')->name('google.groups.members.update');

        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
        Route::resource('presets', 'Google\GroupPresetController', ['as' => 'google.groups']);

        Route::get('{group}', 'Google\GroupController@show')->name('google.groups.show');
    });

    Route::prefix('whatis')->name('google.whatis.')->group(function () {
        Route::get('/', 'Google\WhatisController@index')->name('index');
        Route::post('/search', 'Google\WhatisController@search')->name('search');
    });

    /*
        Route::group(['prefix' => 'calendars'], function() {
            Route::get('/', 'GoogleApiController@getAllCalendars')->name('google.calendars');
            Route::post('/', 'GoogleApiController@getAllCalendars')->name('google.calendars');

        });
    */



    // Route::get('/statistics', '\Uncgits\CcpsApiLog\Http\Controllers\StatisticsController@index')->name('statistics')->middleware('permission:gsuite.view');
});

// Route::group(['prefix' => 'compromised', 'middleware' => ['auth']], function () {
//     Route::get('/', 'CompromisedController@index')->name('compromised');
//     Route::get('/process', 'CompromisedController@process')->name('compromised.process');
// });

app/GoogleGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class GoogleGroup extends Model
{
    use HasFactory, Sortable;

    public $sortable = [
        'google_id',
        'name',
        'email',
        'members_count'
    ];

    protected $primaryKey = 'google_id';
    public $incrementing = false;

    protected $guarded = [];

    protected $casts = [
        'group_object'    => 'object',
        'settings_object' => 'object',
    ];

    // accessores

    public function getIdAttribute()
    {
        return $this->google_id;
    }

    // other

    public function getMembers()
    {
        return collect(\GoogleApi::listGroupMembers($this->email));
    }
}

app/Http/Controllers/Api/GroupController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Google_Service_Exception;

class GroupController extends Controller
{
    private function parseGroupname($group)
    {
        if (strpos($group, '@') !== false) {
            return $group;
        }
        return $group . '@' . config('google-api.domain');
    }

    private function parseUsername($username)
    {
        if (strpos($username, '@') !== false) {
            return $username;
        }
        return $username . '@' . config('google-api.domain');
    }

    public function get($group)
    {
        try {
            $group = \GoogleApi::getGroup($this->parseGroupname($group));
            return response()->json(['query' => $group, 'group' => $group], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function getGroupMember($group, $username)
    {
        try {
            $member = \GoogleApi::getGroupMember($this->parseGroupname($group), $this->parseGroupname($username));
            return response()->json(['query' => $group, 'member' => $member], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function hasGroupMember($group, $username)
    {
        try {
            $member = \GoogleApi::hasGroupMember($this->parseGroupname($group), $this->parseGroupname($username));
            return response()->json(['query' => $group, 'member' => $member], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function getGroupSettings($group)
    {
        try {
            $group = \GoogleApi::getGroupSettings($this->parseGroupname($group));
            return response()->json(['query' => $group, 'group' => $group], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function listGroupMembers($group)
    {
        try {
            $members = \GoogleApi::listGroupMembers($this->parseGroupname($group));
            return response()->json(['query' => $group, 'members' => $members], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }
}

resources/views/google/groups/presets/create.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Group Presets | Create'
])

@section('content')
    <h1>Create Group Preset</h1>
    {!! Form::route('google.groups.presets.store')->method('post')->open() !!}
        {!! Form::text('name', 'Name')->required()->help('A name to help you recognize this Preset') !!}
        <h2>Settings:</h2>
        <div class="row">
            @foreach ($settings as $setting)
                <div class="col-3">{!! Form::select('settings[' . $setting->key . ']', $setting->key, array_merge(['' => 'NOT SET'], $setting->valuesAsOptions))->required(false) !!}</div>
            @endforeach
        </div>
        {!! Form::submit('<i class="fas fa-check"></i> Submit')->color('success') !!}
    {!! Form::close() !!}
@endsection

resources/views/google/groups/presets/edit.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Group Presets | Edit'
])

@section('content')
    <h1>Edit Preset: {{ $preset->name }}</h1>
    {!! Form::route('google.groups.presets.update', ['preset' => $preset->id])->method('patch')->open() !!}
        {!! Form::text('name', 'Name', $preset->name)->required()->help('A name to help you recognize this Preset') !!}
        <h2>Settings:</h2>
        <div class="row">
            @foreach ($settings as $setting)
                <div class="col-3">{!! Form::select('settings[' . $setting->key . ']', $setting->key, array_merge(['' => 'NOT SET'], $setting->valuesAsOptions), $preset->getSettingValue($setting->key))->required(false) !!}</div>
            @endforeach
        </div>
        {!! Form::submit('<i class="fas fa-check"></i> Submit')->color('success') !!}
    {!! Form::close() !!}
@endsection

resources/views/google/groups/presets/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Group Presets | Index'
])

@section('content')
    <div class="d-flex justify-content-between align-items-center">
        <h1>Group Presets</h1>
        <a href="{{ route('google.groups.presets.create') }}" class="btn btn-success">
            <i class="fas fa-plus"></i> Create New
        </a>
    </div>
    <p><strong>Group Presets</strong> are collections of settings that can be applied when creating new groups in this application. They can be customized to suit business needs. Available options are based on non-deprecated API options (complete list here: <a href="https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#resource" target="_blank">https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#resource</a>)</p>
    @if ($presets->isNotEmpty())
        @component('components.table')
            @slot('th')
                <th>ID</th>
                <th>Created By</th>
                <th>Name</th>
                <th># of Settings</th>
                <th>Created At</th>
                <th>Actions</th>
            @endslot

            @slot('tbody')
                @foreach ($presets as $preset)
                    <tr>
                        <td>{{ $preset->id }}</td>
                        <td>{{ $preset->created_by->email }}</td>
                        <td>{{ $preset->name }}</td>
                        <td>
                            {{ $preset->settings->count() }}
                            @component('components.modal', [
                                'title' => $preset->name . ': Settings',
                                'id' => 'preset_' . $preset->id . '_settings',
                            ])
                                @slot('content')
                                    <ul>
                                        @foreach ($preset->settings as $setting)
                                            <li>{{ $setting->key }} - {{ $setting->pivot->value }}</li>
                                        @endforeach
                                    </ul>
                                @endslot
                            @endcomponent
                            <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#preset_{{ $preset->id }}_settings"> <i class="fas fa-eye"></i> Show</button>
                        </td>
                        <td>{{ $preset->created_at }}</td>
                        <td class="d-flex">
                            <a href="{{ route('google.groups.presets.edit', $preset->id) }}" class="btn btn-warning btn-sm mr-2">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            {!! Form::route('google.groups.presets.destroy', ['preset' => $preset->id])->method('delete')->open() !!}
                            <button class="btn btn-danger btn-sm" onclick="return confirm('Are you sure? This cannot be undone.');">
                                <i class="fas fa-trash"></i> Delete
                            </button>
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            @endslot
        @endcomponent
    @endif
@endsection