routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'CcpsCore\HomeController@index')->name('home');
Route::get('home', 'CcpsCore\HomeController@index');

Route::group(['prefix' => 'account'], function () {
    Route::get('/', 'CcpsCore\AccountController@index')->name('account');
    Route::get('/settings', 'CcpsCore\AccountController@settings')->name('account.settings');
    Route::post('/settings', 'CcpsCore\AccountController@updateSettings')->name('account.settings.update');
    Route::get('/profile', 'CcpsCore\AccountController@profile')->name('profile.show');
    Route::get('/profile/edit', 'CcpsCore\AccountController@editProfile')->name('profile.edit');
    Route::patch('/profile/', 'CcpsCore\AccountController@updateProfile')->name('profile.update');

    Route::prefix('tokens')->name('account.tokens.')->group(function () {
        Route::get('/', 'CcpsCore\AccountController@tokens')->name('index');
        Route::get('create', 'CcpsCore\AccountController@createToken')->name('create');
        Route::post('/', 'CcpsCore\AccountController@storeToken')->name('store');
        Route::get('{token}', 'CcpsCore\AccountController@editToken')->name('edit');
        Route::patch('{token}', 'CcpsCore\AccountController@updateToken')->name('update');
        Route::delete('{token}', 'CcpsCore\AccountController@revokeToken')->name('revoke');
    });

    Route::group(['prefix' => 'notifications'], function () {
        Route::get('/', 'CcpsCore\AccountController@notifications')->name('account.notifications.index');
        Route::get('/channels/create', 'CcpsCore\AccountController@createChannel')->name('account.notifications.channels.create');
        Route::post('/channels/create', 'CcpsCore\AccountController@storeChannel')->name('account.notifications.channels.store');
        Route::delete('/channels/{channel}', 'CcpsCore\AccountController@destroyChannel')->name('account.notifications.channels.destroy');
        Route::get(
            '/channels/{channel}/resend-verification',
            'CcpsCore\ChannelVerificationController@resend'
        )->name('account.notifications.channels.resend-verification');
        Route::get(
            '/channels/{channel}/verify',
            'CcpsCore\ChannelVerificationController@verify'
        )->name('account.notifications.channels.verify');
        Route::get(
            '/channels/{channel}/test',
            'CcpsCore\ChannelVerificationController@test'
        )->name('account.notifications.channels.test');

        Route::get('/configure', 'CcpsCore\AccountController@configure')->name('account.notifications.configure');
        Route::post('/configure', 'CcpsCore\AccountController@configureSave')->name('account.notifications.configure.save');
    });
});

// CCPS Core routes
Uncgits\Ccps\Support\Facades\CcpsCore::routes();
// For local auth
Auth::routes();

// Socialite - User Account OAuth Routes
Route::get('auth/{provider}', 'CcpsCore\AuthController@redirectToProvider')->name('oauth');
Route::get('auth/{provider}/callback', 'CcpsCore\AuthController@handleProviderCallback')->name('oauth.callback');


// Route::get('apistats', '\Uncgits\CcpsApiLog\Http\Controllers\StatisticsController@index');


// -----------------------
// Google Viewer app routes
// -----------------------

Route::group(['prefix' => 'google', 'middleware' => ['auth']], function () {
    Route::get('/', 'GoogleController@index')->name('google');
    Route::get('/info', 'GoogleController@info')->name('google.info');
    Route::group(['prefix' => 'activity'], function () {
        Route::get('/', 'GoogleController@getActivity')->name('google.activity.index');
        Route::post('/', 'GoogleController@getActivity')->name('google.activity.index');

        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
    });
    Route::group(['prefix' => 'users'], function () {
        Route::post('/suspend', 'GoogleController@suspendUser')->name('google.users.suspend');

        Route::get('/show/', 'GoogleController@showUser')->name('google.users.show');

        Route::get('bulk-rename', 'Google\BulkActionController@rename')->name('google.users.bulk-rename');
        Route::post('bulk-rename', 'Google\BulkActionController@confirmRename')->name('google.users.bulk-rename-confirm');
        Route::post('bulk-rename/confirm', 'Google\BulkActionController@performRename')->name('google.users.bulk-rename-perform');

        Route::get('bulk-delete', 'Google\BulkActionController@delete')->name('google.users.bulk-delete');
        Route::post('bulk-delete', 'Google\BulkActionController@confirmDelete')->name('google.users.bulk-delete-confirm');
        Route::post('bulk-delete/confirm', 'Google\BulkActionController@performDelete')->name('google.users.bulk-delete-perform');

        Route::get('/admins', 'GoogleController@getAdmins');
        Route::get('/{key}', 'GoogleController@showUser')->name('google.users.key');
        Route::get('/{key}/logins', 'GoogleController@showUserLogins')->name('google.users.logins');
        Route::get('/{key}/email/', 'Google\UserEmailController@showUserEmail')->name('google.users.email');
        Route::get('/{key}/groups/', 'Google\UserGroupsController@showUserGroups')->name('google.users.groups');

        Route::get('/', 'GoogleController@getUsers')->name('google.users.index');

        Route::post('/', 'GoogleController@getUsers')->name('google.users.index');


        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
    });
    Route::group(['prefix' => 'groups'], function () {
        Route::get('/', 'Google\GroupController@index')->name('google.groups.index');
        Route::get('create', 'Google\GroupController@create')->name('google.groups.create');
        Route::get('sync', 'Google\GroupController@sync')->name('google.groups.sync');
        Route::get('all', 'Google\GroupController@all')->name('google.groups.all');
        Route::post('store', 'Google\GroupController@store')->name('google.groups.store');
        Route::get('{group}/edit', 'Google\GroupController@edit')->name('google.groups.edit');
        Route::post('{group}/edit', 'Google\GroupController@update')->name('google.groups.update');

        Route::get('/queue', 'Google\GroupController@getQueue')->name('google.groups.queue');

        Route::get('{group}/members', 'Google\GroupController@editMembers')->name('google.groups.members.edit');
        Route::post('{group}/members', 'Google\GroupController@updateMembers')->name('google.groups.members.update');

        // Route::get('/all', 'GoogleController@usersAll')->name('google.users.all');
        //  Route::get('/active', 'GoogleController@usersActive')->name('google.users.active');
        //  Route::get('/search', 'GoogleController@usersSearch')->name('google.users.search');
        Route::resource('presets', 'Google\GroupPresetController', ['as' => 'google.groups']);

        Route::get('{group}', 'Google\GroupController@show')->name('google.groups.show');
    });

    Route::prefix('whatis')->name('google.whatis.')->group(function () {
        Route::get('/', 'Google\WhatisController@index')->name('index');
        Route::post('/search', 'Google\WhatisController@search')->name('search');
    });

    /*
        Route::group(['prefix' => 'calendars'], function() {
            Route::get('/', 'GoogleApiController@getAllCalendars')->name('google.calendars');
            Route::post('/', 'GoogleApiController@getAllCalendars')->name('google.calendars');

        });
    */



    // Route::get('/statistics', '\Uncgits\CcpsApiLog\Http\Controllers\StatisticsController@index')->name('statistics')->middleware('permission:gsuite.view');
});

// Route::group(['prefix' => 'compromised', 'middleware' => ['auth']], function () {
//     Route::get('/', 'CompromisedController@index')->name('compromised');
//     Route::get('/process', 'CompromisedController@process')->name('compromised.process');
// });

app/GoogleGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class GoogleGroup extends Model
{
    use HasFactory, Sortable;

    public $sortable = [
        'google_id',
        'name',
        'email',
        'members_count'
    ];

    protected $primaryKey = 'google_id';
    public $incrementing = false;

    protected $guarded = [];

    protected $casts = [
        'group_object'    => 'object',
        'settings_object' => 'object',
    ];

    // accessores

    public function getIdAttribute()
    {
        return $this->google_id;
    }

    // other

    public function getMembers()
    {
        return collect(\GoogleApi::listGroupMembers($this->email));
    }
}

app/Http/Controllers/Api/GroupController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Google_Service_Exception;

class GroupController extends Controller
{
    private function parseGroupname($group)
    {
        if (strpos($group, '@') !== false) {
            return $group;
        }
        return $group . '@' . config('google-api.domain');
    }

    private function parseUsername($username)
    {
        if (strpos($username, '@') !== false) {
            return $username;
        }
        return $username . '@' . config('google-api.domain');
    }

    public function get($group)
    {
        try {
            $group = \GoogleApi::getGroup($this->parseGroupname($group));
            return response()->json(['query' => $group, 'group' => $group], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function getGroupMember($group, $username)
    {
        try {
            $member = \GoogleApi::getGroupMember($this->parseGroupname($group), $this->parseGroupname($username));
            return response()->json(['query' => $group, 'member' => $member], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function hasGroupMember($group, $username)
    {
        try {
            $member = \GoogleApi::hasGroupMember($this->parseGroupname($group), $this->parseGroupname($username));
            return response()->json(['query' => $group, 'member' => $member], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function getGroupSettings($group)
    {
        try {
            $group = \GoogleApi::getGroupSettings($this->parseGroupname($group));
            return response()->json(['query' => $group, 'group' => $group], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    public function listGroupMembers($group)
    {
        try {
            $members = \GoogleApi::listGroupMembers($this->parseGroupname($group));
            return response()->json(['query' => $group, 'members' => $members], 200);
        } catch (Google_Service_Exception $e) {
            return response()->json(['message' => $e->getMessage(), 'code' => $e->getCode()], $e->getCode());
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }
}

app/Http/Controllers/Google/EmailController.php
<?php

namespace App\Http\Controllers\Google;

use App\Http\Controllers\Controller as BaseController;

use Illuminate\Http\Request;
use App\GoogleApi;
use Google_Service_Exception;

class EmailController extends BaseController
{
  
    /*
   |----------------------------------------------
   | Constructor
   |----------------------------------------------
   */

    public function __construct()
    {
        $this->googleApi = new GoogleApi();
        $this->middleware('permission:gsuite.*')->only(['index']);
        $this->middleware('permission:gsuite.users.view')->only(['getUsers', 'getAdmins', 'showUser']);
        $this->middleware('permission:gsuite.users.delete')->only(['suspendUser']);
    }



    public function showEmailConfig(Request $request)
    {
        // Validation stuff
        if (isset($request->key) && !empty($request->key)) {
            try {
                $userInfo = $this->googleApi->getUser($request->key);
                $userPhoto = $this->googleApi->getUserPhoto($request->key, true);
                $userAliases = $this->googleApi->listUserAliases($request->key);
                $emailForwards = $this->googleApi->listEmailForwards($request->key);
                $emailFilters = $this->googleApi->listEmailFilters($request->key);
                $emailDelegates = $this->googleApi->listEmailDelegates($request->key);
                $emailLabels = $this->googleApi->listEmailLabels($request->key);

                return view('google.users.email', compact('userInfo', 'userPhoto', 'userAliases', 'emailForwards', 'emailFilters', 'emailDelegates', 'emailLabels', 'request'));
            } catch (Google_Service_Exception $e) {
                flash('User not found in domain - this user may be external.');
                return view('google.users.show')->with([
                'userInfo' => ''
            ]);
            }
        }
    }
}

app/Http/Controllers/Google/UserEmailController.php
<?php

namespace App\Http\Controllers\Google;

use App\Http\Controllers\Controller as BaseController;

use Illuminate\Http\Request;
use App\GoogleApi;
use Google_Service_Exception;

class UserEmailController extends BaseController
{

    /*
   |----------------------------------------------
   | Constructor
   |----------------------------------------------
   */

    public function __construct()
    {
        $this->googleApi = new GoogleApi();
        $this->middleware('permission:gsuite.*')->only(['index']);
        $this->middleware('permission:gsuite.users.view')->only(['getUsers', 'getAdmins', 'showUser']);
        $this->middleware('permission:gsuite.users.delete')->only(['suspendUser']);
    }



    public function showUserEmail(Request $request)
    {
        // Validation stuff
        if (isset($request->key) && !empty($request->key)) {
            try {
                $userInfo = $this->googleApi->getUser($request->key);
                $userPhoto = $this->googleApi->getUserPhoto($request->key, true);
                $userAliases = $this->googleApi->listUserAliases($request->key);
                $emailForwards = $this->googleApi->listEmailForwards($request->key);
                $emailFilters = $this->googleApi->listEmailFilters($request->key)->filter ?? [];
                $emailDelegates = $this->googleApi->listEmailDelegates($request->key);
                $emailLabels = $this->googleApi->listEmailLabels($request->key);
                $emailVacation = $this->googleApi->getEmailVacation($request->key);
                $emailSendAs = $this->googleApi->getEmailSendAs($request->key);
                $emailLanguage = $this->googleApi->getEmailLanguage($request->key);
                $emailPop = $this->googleApi->getEmailPop($request->key);
                $emailImap = $this->googleApi->getEmailImap($request->key);
                $emailProfile = $this->googleApi->getEmailProfile($request->key);

                return view('google.users.email', compact(
                    'userInfo',
                    'userPhoto',
                    'userAliases',
                    'emailForwards',
                    'emailFilters',
                    'emailDelegates',
                    'emailLabels',
                    'emailVacation',
                    'emailSendAs',
                    'emailLanguage',
                    'emailPop',
                    'emailImap',
                    'emailProfile',
                    'request'
                ));
            } catch (Google_Service_Exception $e) {
                flash('User not found in domain - this user may be external.');
                return view('google.users.show')->with([
                'userInfo' => ''
            ]);
            }
        }
    }
}

resources/views/google/groups/all.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Google Users'
])

@section('content')
    {!! Breadcrumbs::render('google_groups_all') !!}

    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h1>All Google Groups</h1>
            <p>This page lists every Google Group in the domain</p>
        </div>
    </div>

    @if(!empty($groups))
        @component('components.table')
            @slot('th')
                <th scope="col">@sortablelink('google_id','ID')</th>
                <th scope="col">@sortablelink('email','Email')</th>
                <th scope="col">@sortablelink('name', 'Name')</th>
                <th scope="col">@sortablelink('members_count', 'Members')</th>
                <th scope="col">Actions</th>
            @endslot
            @slot('tbody')
                @foreach ($groups as $thisGroup)
                    <tr>
                        <td>{{ $thisGroup->id }}</td>
                        <td>{{ $thisGroup->email }}</td>
                        <td>{{ $thisGroup->name}}</td>
                        <td>{{ $thisGroup->members_count }}</td>
                        <td class="d-flex flex-column flex-md-row">
                            <a href="{{ route('google.groups.show', $thisGroup) }}" class="btn btn-sm btn-primary mr-2 mb-2 mb-md-0"><i class="fas fa-list"></i> Details</a>

                        </td>
                    </tr>
                @endforeach
            @endslot
        @endcomponent
    @else
        <p>No groups returned.</p>
    @endif
@endsection()

resources/views/google/groups/index.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Google Users'
])

@section('content')
    {!! Breadcrumbs::render('google_groups') !!}

    <div class="d-flex justify-content-between align-items-center">
        <div>
            <h1>Google Groups</h1>
        </div>
        <div class="d-flex justify-content-end align-items-center">
            <a href="{{ route('google.groups.create') }}" class="btn btn-sm btn-success"><i class="fas fa-plus"></i> Add New</a>
            <a href="{{ route('google.groups.all') }}" class="ml-2 btn btn-sm btn-warning"><i class="fas fa-list"></i> Show All</a>
            <a href="{{ route('google.groups.presets.index') }}" class="ml-2 btn btn-sm btn-dark"><i class="fas fa-cogs"></i> Presets</a>
            <a href="{{ route('google.groups.sync') }}" class="ml-2 btn btn-sm btn-info"><i class="fas fa-sync"></i> Sync from Google</a>
        </div>
    </div>
    <p>This list shows the local Group cache, which is synced regularly. You can manually sync it using the button at the upper-right.</p>

    <div class="row mb-3">
        <div class="col">
            <div class="card">
                <div class="card-header">Search / Filter</div>
                <div class="card-body">
                    {!! Form::open()->inlineForm()->get()->route('google.groups.index')->fill(collect(request()->except('_token'))) !!}
                    {!! Form::text('email', 'Email')->placeholder('Email') !!}
                    {!! Form::text('name', 'Name')->placeholder('Name') !!}
                    {!! Form::submit('<i class="fas fa-search"></i> Search')->size('sm')->color('success') !!}
                    {!! Form::anchor('<i class="fas fa-undo"></i> Reset', route('google.groups.index'))->size('sm')->color('danger') !!}
                    {!! Form::close() !!}
                </div>
            </div>

        </div>
    </div>

    @if (request()->anyFilled(['name', 'email']))
        <div class="alert alert-warning">
            <i class="fas fa-exclamation-circle"></i> Filtering on
        </div>
    @endif

    @if(!empty($groups))

        @component('components.paginated-table', ['collection' => $groups, 'appends' => [
            'name' => request('name', ''),
            'email' => request('email', '')
        ]])
            @slot('table')
                @component('components.table')
                    @slot('th')
                        <th scope="col">@sortablelink('google_id','ID')</th>
                        <th scope="col">@sortablelink('email','Email')</th>
                        <th scope="col">@sortablelink('name', 'Name')</th>
                        <th scope="col">@sortablelink('members_count', 'Members')</th>
                        <th scope="col">Actions</th>
                    @endslot
                    @slot('tbody')
                        @foreach ($groups as $thisGroup)
                            <tr>
                                <td>{{ $thisGroup->id }}</td>
                                <td>{{ $thisGroup->email }}</td>
                                <td>{{ $thisGroup->name}}</td>
                                <td>{{ $thisGroup->members_count }}</td>
                                <td class="d-flex flex-column flex-md-row">
                                    <a href="{{ route('google.groups.show', $thisGroup) }}" class="btn btn-sm btn-primary mr-2 mb-2 mb-md-0"><i class="fas fa-list"></i> Details</a>

                                </td>
                            </tr>
                        @endforeach
                    @endslot
                @endcomponent
            @endslot
        @endcomponent

    @else
        <p>No groups returned.</p>
    @endif
@endsection()

resources/views/google/groups/members.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Google Group Membership Edit'
])

@section('content')
    {!! Breadcrumbs::render('google_groups_show', $group) !!}

    <h1>Google Group Membership Edit</h1>
    @if(!empty($group))
        <div class="card mb-3">

            <h5 class="card-header">Group Information</h5>
            <div class="card-body">

        <h2>{{ $group->name }} // {{ $group->email }}</h2>

        <form method="POST" action="{{ route('google.groups.members.update', $group) }}" enctype="application/x-www-form-urlencoded">
            {{ csrf_field() }}

            <div class="form-group row">
                <label for="ownerEmail" class="col-sm-2 col-form-label">List of email addresses (or usernames if using default domain):</label>
                <div class="col-sm-10">
                    <textarea name="emailList" id="emailList" style="width: 50%; height: 150px;" class="" rows="24" cols="80"  aria-describedby="emailListHelpBlock"></textarea>
                    <small id="emaiListHelpBlock" class="form-text text-muted">Enter each email address on a line by itself (no quotes, commas or spaces)</small>
                </div>
            </div>

            <div class="form-group row">
                <label for="groupRole" class="col-sm-2 col-form-label">Group Role</label>
                <div class="col-sm-10">

                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="groupRole" id="groupRole-Owner" value="OWNER">
                            <label class="form-check-label" for="groupRole-Owner">OWNER</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="groupRole" id="groupRole-Member" value="MEMBER"   checked="checked">
                            <label class="form-check-label" for="groupRole-Member">MEMBER</label>
                        </div>


                </div>
            </div>

            <div class="form-group row">
                <label for="groupRole" class="col-sm-2 col-form-label">Action Type</label>
                <div class="col-sm-10">

                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="action" id="action-add" value="ADD" checked="checked">
                        <label class="form-check-label" for="action-add">Add these Users</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="action" id="action-delete" value="DELETE">
                        <label class="form-check-label" for="action-delete">Delete these Users</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="action" id="action-replace" value="REPLACE"   >
                        <label class="form-check-label" for="action-replace">Replace current membership with these Users</label>
                    </div>


                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Submit</button>
                        <input type="hidden" name="groupId" id="groupId" value="{{ $group->id }}">
                        <a href="{{ route('google.groups.show', $group) }}" class="btn btn-danger"><i class="fas fa-times"></i> Cancel</a>
                    </div>
                </div>
            </div>
        </form>

        <div class="card mb-3">

        <h5 class="card-header">Membership</h5>
        <div class="card-body">
        @if($groupMembers->isNotEmpty())
            @include('partials.groups.member-table')
        @else
            <p>No Members.</p>
        @endif

        @else
        <p>Error: No Group ID.</p>
        @endif

        </div>
    </div>

@endsection()

resources/views/google/groups/show.blade.php
@extends('layouts.wrapper', [
    'pageTitle' => 'Google Group Detail'
])

@section('content')
    {!! Breadcrumbs::render('google_groups_show', $group) !!}

    <h1>Google Group Details</h1>
    @if(!empty($groupSettings))
    <div class="card mb-3">

        <h5 class="card-header">Group Information</h5>
        <div class="card-body">
        <h2>{{ $groupSettings->name }} // {{ $groupSettings->email }}</h2>

        <p><strong>Description:</strong>
            @if(!empty($groupSettings->description)) {{ $groupSettings->description }} @else <em>no description provided</em>@endif</p>
        <h4>Settings:</h4>
            <ul>
                <li>Who Can Moderate Members: {{ $groupSettings->whoCanModerateMembers }} </li>
                <li>Who Can Join: {{ $groupSettings->whoCanJoin }} </li>

                <li>Who Can Leave: {{ $groupSettings->whoCanLeaveGroup }} </li>
                <li>Who Can View Memberships: {{ $groupSettings->whoCanViewMembership }} </li>
                <li>Who Can View Group: {{ $groupSettings->whoCanViewGroup }} </li>
                <li>Who Can Invite: {{ $groupSettings->whoCanInvite }} </li>
                <li>Who Can Post Messages: {{ $groupSettings->whoCanPostMessage }} </li>
                <li>Is Archived?  @if ($groupSettings->isArchived == "true") YES  // TRUE @else NO // FALSE @endif </li>
                <li>Allow Web Postings?  @if ($groupSettings->allowWebPosting == "true") YES  // TRUE @else NO // FALSE @endif </li>
                <li>Allow External Members?  @if ($groupSettings->allowExternalMembers == "true") YES // TRUE @else NO // FALSE @endif </li>
                <li>Who Can Discover Group: {{ $groupSettings->whoCanDiscoverGroup }}</li>
                <li>Include in Global Address List?  @if ($groupSettings->includeInGlobalAddressList == "true") YES // TRUE @else NO // FALSE @endif </li>
                <li>Collaborative Inbox?  @if ($groupSettings->enableCollaborativeInbox == "true") YES // TRUE @else NO // FALSE @endif </li>

            </ul>
                <a href="{{ route('google.groups.edit', $group) }}" class="btn btn-warning"><i class="fa fa-edit"></i> Update</a>
                <a href="{{ $groupWebUrl }}" class="btn btn btn-primary mr-2 mb-2 mb-md-0"><i class="fas fa-mouse-pointer"></i> View Group on Web</a>


    @else
        <p>No Group Information/Settings returned.</p>
    @endif



        </div>
    </div>
    <div class="card mb-3">

        <h5 class="card-header">Membership</h5>
        <div class="card-body">
            <p>
                <a href="{{ route('google.groups.members.edit', $group) }}" class="btn btn-warning"><i class="fa fa-edit"></i> Update</a>
            </p>
        @if($groupMembers->isNotEmpty())
            @include('partials.groups.member-table')
        @else
            <p>No Members.</p>
        @endif
        </div>
    </div>





@endsection()